spring.application.name=DianSoap

server.port=8080

# SOAP
app.soap.target-namespace=http://dian.soap/Factura

# Mail (disabled by default to avoid runtime errors)
app.mail.enabled=false
spring.mail.host=
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
